from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import os
from datetime import datetime
import tempfile

class ReportGenerator:
    def __init__(self, analysis_data):
        self.data = analysis_data
        self.styles = getSampleStyleSheet()
        
    def generate(self):
        """Generate PDF report"""
        temp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.pdf')
        doc = SimpleDocTemplate(
            temp_file.name,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        story = []
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.HexColor('#00ffff')
        )
        story.append(Paragraph("NexaImage Forensics Report", title_style))
        story.append(Spacer(1, 12))
        
        # Report metadata
        story.append(Paragraph(f"Report ID: {self.data.get('analysis_id', 'N/A')}", self.styles['Normal']))
        story.append(Paragraph(f"Analysis Date: {self.data.get('analysis_date', 'N/A')}", self.styles['Normal']))
        story.append(Spacer(1, 20))
        
        # File Information
        story.append(Paragraph("File Information", self.styles['Heading2']))
        file_info = self.data.get('file_info', {})
        file_data = [
            ['Property', 'Value'],
            ['Filename', file_info.get('filename', 'N/A')],
            ['File Size', file_info.get('size_formatted', 'N/A')],
            ['Extension', file_info.get('extension', 'N/A')]
        ]
        
        t = Table(file_data, colWidths=[200, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a1a2e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#00ffff')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#16213e')),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#0f3460')),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.white),
        ]))
        story.append(t)
        story.append(Spacer(1, 20))
        
        # Hashes
        story.append(Paragraph("Cryptographic Hashes", self.styles['Heading2']))
        hashes = self.data.get('hashes', {})
        hash_data = [['Algorithm', 'Hash Value']]
        for algo, value in hashes.items():
            hash_data.append([algo.upper(), value])
        
        t = Table(hash_data, colWidths=[100, 400])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a1a2e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#00ffff')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#16213e')),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#0f3460')),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.white),
        ]))
        story.append(t)
        story.append(Spacer(1, 20))
        
        # Security Analysis
        story.append(Paragraph("Security Analysis", self.styles['Heading2']))
        security = self.data.get('security_analysis', {})
        risk = security.get('risk_indicator', {})
        story.append(Paragraph(f"Risk Level: {risk.get('level', 'Unknown')} (Confidence: {risk.get('confidence', 'N/A')})", self.styles['Normal']))
        story.append(Spacer(1, 20))
        
        # Footer
        story.append(Spacer(1, 30))
        story.append(Paragraph("Generated by NexaSecure Tech", self.styles['Normal']))
        story.append(Paragraph("https://www.nexasecure.tech", self.styles['Normal']))
        story.append(Paragraph("© 2026 NexaSecure Tech. All Rights Reserved.", self.styles['Normal']))
        
        # Build PDF
        doc.build(story)
        return temp_file.name